// <auto-generated />
using System;
using FinalProjectApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProjectApp.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20240426150755_AddNewBookData")]
    partial class AddNewBookData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProjectApp.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("AuthorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isbn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PublishYear")
                        .HasColumnType("int");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorName = "Sylvia Plath",
                            BookName = "The Bell Jar",
                            Img = "",
                            Isbn = "5897",
                            PublishYear = 1963
                        },
                        new
                        {
                            BookId = 2,
                            AuthorName = "Sylvia Plath",
                            BookName = "Lady Lazarus",
                            Img = "",
                            Isbn = "5897",
                            PublishYear = 1965
                        },
                        new
                        {
                            BookId = 3,
                            AuthorName = "Sylvia Plath",
                            BookName = "Ariel",
                            Img = "",
                            Isbn = "5897",
                            PublishYear = 1965
                        },
                        new
                        {
                            BookId = 4,
                            AuthorName = "Sylvia Plath",
                            BookName = "Sylvia Plath: Poems",
                            Img = "",
                            Isbn = "5897",
                            PublishYear = 1985
                        },
                        new
                        {
                            BookId = 5,
                            AuthorName = "Sylvia Plath",
                            BookName = "Journals of Sylvia Plath",
                            Img = "",
                            Isbn = "5897",
                            PublishYear = 1982
                        },
                        new
                        {
                            BookId = 6,
                            AuthorName = "Sylvia Plath",
                            BookName = "Tulips",
                            Img = "",
                            Isbn = "5897",
                            PublishYear = 1965
                        },
                        new
                        {
                            BookId = 7,
                            AuthorName = "Jhumpa Lahiri",
                            BookName = "The Namesake",
                            Img = "",
                            Isbn = "8367",
                            PublishYear = 2003
                        },
                        new
                        {
                            BookId = 8,
                            AuthorName = "Jhumpa Lahiri",
                            BookName = "Interpreter of Maladies",
                            Img = "",
                            Isbn = "8367",
                            PublishYear = 1999
                        },
                        new
                        {
                            BookId = 9,
                            AuthorName = "Jhumpa Lahiri",
                            BookName = "Unaccustomed Earth",
                            Img = "",
                            Isbn = "8367",
                            PublishYear = 2008
                        },
                        new
                        {
                            BookId = 10,
                            AuthorName = "Jhumpa Lahiri",
                            BookName = "Roman Stories",
                            Img = "",
                            Isbn = "8367",
                            PublishYear = 2023
                        },
                        new
                        {
                            BookId = 11,
                            AuthorName = "Jhumpa Lahiri",
                            BookName = "The Lowland",
                            Img = "",
                            Isbn = "8367",
                            PublishYear = 2013
                        },
                        new
                        {
                            BookId = 12,
                            AuthorName = "Jhumpa Lahiri",
                            BookName = "Whereabouts",
                            Img = "",
                            Isbn = "8367",
                            PublishYear = 2018
                        },
                        new
                        {
                            BookId = 13,
                            AuthorName = "Jhumpa Lahiri",
                            BookName = "The Other Words",
                            Img = "",
                            Isbn = "8367",
                            PublishYear = 2015
                        },
                        new
                        {
                            BookId = 14,
                            AuthorName = "Jhumpa Lahiri",
                            BookName = "Hell-Heaven",
                            Img = "",
                            Isbn = "8367",
                            PublishYear = 2015
                        },
                        new
                        {
                            BookId = 15,
                            AuthorName = "Jhumpa Lahiri",
                            BookName = "Only Goodness",
                            Img = "",
                            Isbn = "8367",
                            PublishYear = 2013
                        },
                        new
                        {
                            BookId = 16,
                            AuthorName = "Jhumpa Lahiri",
                            BookName = "The Clothing of Books",
                            Img = "",
                            Isbn = "8367",
                            PublishYear = 2016
                        },
                        new
                        {
                            BookId = 17,
                            AuthorName = "Stephen King",
                            BookName = "It",
                            Img = "",
                            Isbn = "1648",
                            PublishYear = 1986
                        },
                        new
                        {
                            BookId = 18,
                            AuthorName = "Stephen King",
                            BookName = "The Shining",
                            Img = "",
                            Isbn = "1648",
                            PublishYear = 1977
                        },
                        new
                        {
                            BookId = 19,
                            AuthorName = "Stephen King",
                            BookName = "Holly",
                            Img = "",
                            Isbn = "1648",
                            PublishYear = 2023
                        },
                        new
                        {
                            BookId = 20,
                            AuthorName = "Stephen King",
                            BookName = "Carrie",
                            Img = "",
                            Isbn = "1648",
                            PublishYear = 1974
                        },
                        new
                        {
                            BookId = 21,
                            AuthorName = "Stephen King",
                            BookName = "The Stand",
                            Img = "",
                            Isbn = "1648",
                            PublishYear = 1978
                        },
                        new
                        {
                            BookId = 22,
                            AuthorName = "Stephen King",
                            BookName = "Misery",
                            Img = "",
                            Isbn = "1648",
                            PublishYear = 1987
                        });
                });

            modelBuilder.Entity("FinalProjectApp.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReviewId");

                    b.ToTable("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
